/**
 * 页面跳转
 */
export const BACK = "BACK";

export const NA_TEST_PAGE = "NA_TEST_PAGE";

export const APP_CHANGE_STATE = "APP_CHANGE_STATE";

export const DRAWER_CHANGE_STATE = "DRAWER_CHANGE_STATE";

export const TEST_SCREEN_CHANGE_STATE = "TEST_SCREEN_CHANGE_STATE";

export const MAIN_SCREEN_CHANGE_STATE = "MAIN_SCREEN_CHANGE_STATE";

export const NEWS_CHANGE_STATE = "NEWS_CHANGE_STATE";

export const TREATY_CHANGE_STATE = "TREATY_CHANGE_STATE";

export const SERVICE_CHANGE_STATE = "SERVICE_CHANGE_STATE";

export const CONSULTATION_CHANGE_STATE = "CONSULTATION_CHANGE_STATE";
